[build]
builder = "dockerfile"

[deploy]
startCommand = "npm run preview -- --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.variables]
NODE_ENV = "production"
