[build]
builder = "dockerfile"
dockerfilePath = "frontend/Dockerfile"

[deploy]
startCommand = "npm run preview -- --port $PORT --no-open"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[deploy.environment]
PORT = "3000"
NODE_ENV = "production"
