[build]
builder = "dockerfile"
dockerfilePath = "frontend/Dockerfile"
context = "."

[deploy]
startCommand = "serve dist -l 3000"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[deploy.environment]
PORT = "3000"
NODE_ENV = "production"
