decision_engine:
  static_weight: 0.6   # 静态分析权重
  dynamic_weight: 0.4  # 动态分析权重
  
risk_levels:
  terminate: 75        # 终止阈值
  warning: 40          # 警告阈值

ai_config:
  model: "gpt-3.5-turbo"
  max_tokens: 1000
  temperature: 0.7

response_analysis:
  fuzzy_evasion: 30    # 模糊回避风险值
  emotional_attack: 50 # 情绪攻击风险值
  topic_shift: 25      # 话题转移风险值
  precise_answer: -20  # 精准回答奖励值
