[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
context = "backend"

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
