[build]
builder = "dockerfile"
dockerfilePath = "backend/Dockerfile"

[deploy]
startCommand = "python -m app.main"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[deploy.environment]
PORT = "8000"
DEBUG = "false"
WORKERS = "1"
APP_ENV = "prod"
