[build]
builder = "dockerfile"
dockerfilePath = "project/backend/Dockerfile"
watchPaths = ["."]

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.variables]
ENVIRONMENT = "production"
